[2025-08-06T15:54:29.000+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-06T15:54:29.028+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T15:52:06.777976+00:00 [queued]>
[2025-08-06T15:54:29.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T15:52:06.777976+00:00 [queued]>
[2025-08-06T15:54:29.037+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-06T15:54:29.053+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_jobs_to_minio> on 2025-08-06 15:52:06.777976+00:00
[2025-08-06T15:54:29.062+0000] {standard_task_runner.py:63} INFO - Started process 144 to run task
[2025-08-06T15:54:29.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'jobs_crawler_dag', 'upload_jobs_to_minio', 'manual__2025-08-06T15:52:06.777976+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/crawl_jobs_dag.py', '--cfg-path', '/tmp/tmpgf_wqngf']
[2025-08-06T15:54:29.069+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask upload_jobs_to_minio
[2025-08-06T15:54:29.108+0000] {task_command.py:426} INFO - Running <TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T15:52:06.777976+00:00 [running]> on host 3998357efbd9
[2025-08-06T15:54:29.168+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='jobs_crawler_dag' AIRFLOW_CTX_TASK_ID='upload_jobs_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T15:52:06.777976+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T15:52:06.777976+00:00'
[2025-08-06T15:54:29.169+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-06T15:54:29.626+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-06T15:54:29.627+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/spark/src/elt/load/load_data_to_minio.py", line 43, in upload_jobs_to_minio
    s3.put_object(Bucket=bucket_name, Key=object_key, Body=buffer.getvalue())
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
[2025-08-06T15:54:29.637+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=jobs_crawler_dag, task_id=upload_jobs_to_minio, run_id=manual__2025-08-06T15:52:06.777976+00:00, execution_date=20250806T155206, start_date=20250806T155429, end_date=20250806T155429
[2025-08-06T15:54:29.645+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task upload_jobs_to_minio (An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.; 144)
[2025-08-06T15:54:29.684+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-06T15:54:29.703+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T15:54:29.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
