[2025-08-08T12:26:31.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-08T12:26:31.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-08T12:26:09.298420+00:00 [queued]>
[2025-08-08T12:26:31.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-08T12:26:09.298420+00:00 [queued]>
[2025-08-08T12:26:31.183+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-08T12:26:31.256+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_jobs_to_minio> on 2025-08-08 12:26:09.298420+00:00
[2025-08-08T12:26:31.267+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2025-08-08T12:26:31.270+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'jobs_crawler_dag', 'upload_jobs_to_minio', 'manual__2025-08-08T12:26:09.298420+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/crawl_jobs_dag.py', '--cfg-path', '/tmp/tmpqn0yqln3']
[2025-08-08T12:26:31.272+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask upload_jobs_to_minio
[2025-08-08T12:26:31.412+0000] {task_command.py:426} INFO - Running <TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-08T12:26:09.298420+00:00 [running]> on host 7c97c18d1ccf
[2025-08-08T12:26:31.602+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='jobs_crawler_dag' AIRFLOW_CTX_TASK_ID='upload_jobs_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T12:26:09.298420+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-08T12:26:09.298420+00:00'
[2025-08-08T12:26:31.606+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-08T12:26:33.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-08T12:26:33.718+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2637, in _prep_and_do_upload
    created_json = self._do_upload(
                   ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2460, in _do_upload
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2278, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2152, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/spark/src/elt/load/upload_jobs_to_gcs.py", line 33, in upload_jobs_to_gcs
    blob.upload_from_file(buffer, content_type="application/octet-stream")
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2796, in upload_from_file
    self._prep_and_do_upload(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2655, in _prep_and_do_upload
    _raise_from_invalid_response(exc)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 4847, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/upload/storage/v1/b/job_gcp/o?uploadType=resumable: {
  "error": {
    "code": 403,
    "message": "irflow-spark-service@jobpipeline-468411.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "irflow-spark-service@jobpipeline-468411.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)
[2025-08-08T12:26:33.743+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=jobs_crawler_dag, task_id=upload_jobs_to_minio, run_id=manual__2025-08-08T12:26:09.298420+00:00, execution_date=20250808T122609, start_date=20250808T122631, end_date=20250808T122633
[2025-08-08T12:26:33.775+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task upload_jobs_to_minio (403 POST https://storage.googleapis.com/upload/storage/v1/b/job_gcp/o?uploadType=resumable: {
  "error": {
    "code": 403,
    "message": "irflow-spark-service@jobpipeline-468411.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "irflow-spark-service@jobpipeline-468411.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>); 86)
[2025-08-08T12:26:33.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-08T12:26:33.820+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-08T12:26:33.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
