[2025-08-06T17:15:50.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-06T17:15:50.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T17:15:36.309839+00:00 [queued]>
[2025-08-06T17:15:50.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T17:15:36.309839+00:00 [queued]>
[2025-08-06T17:15:50.762+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-06T17:15:50.781+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_jobs_to_minio> on 2025-08-06 17:15:36.309839+00:00
[2025-08-06T17:15:50.790+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2025-08-06T17:15:50.794+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'jobs_crawler_dag', 'upload_jobs_to_minio', 'manual__2025-08-06T17:15:36.309839+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/crawl_jobs_dag.py', '--cfg-path', '/tmp/tmpu55e2wfw']
[2025-08-06T17:15:50.800+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask upload_jobs_to_minio
[2025-08-06T17:15:50.907+0000] {task_command.py:426} INFO - Running <TaskInstance: jobs_crawler_dag.upload_jobs_to_minio manual__2025-08-06T17:15:36.309839+00:00 [running]> on host 4809f5d70d3c
[2025-08-06T17:15:51.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='jobs_crawler_dag' AIRFLOW_CTX_TASK_ID='upload_jobs_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T17:15:36.309839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T17:15:36.309839+00:00'
[2025-08-06T17:15:51.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-06T17:15:52.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-06T17:15:52.161+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/spark/src/elt/load/load_data_to_minio.py", line 43, in upload_jobs_to_minio
    s3.put_object(Bucket=bucket_name, Key=object_key, Body=buffer.getvalue())
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
[2025-08-06T17:15:52.239+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=jobs_crawler_dag, task_id=upload_jobs_to_minio, run_id=manual__2025-08-06T17:15:36.309839+00:00, execution_date=20250806T171536, start_date=20250806T171550, end_date=20250806T171552
[2025-08-06T17:15:52.258+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task upload_jobs_to_minio (An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.; 209)
[2025-08-06T17:15:52.291+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-06T17:15:52.312+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T17:15:52.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
